services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./src/.env
    volumes:
      - .:/app
    command: ["./bin"]

  db:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dqm50vnc
      POSTGRES_DB: exechub
    volumes:
      - exechub-db:/var/lib/postgresql/data

volumes:
  exechub-db:
