version: "3.2"

services:
  redis:
    image: redis
    ports:
      - "6380:6379"
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    volumes:
      - "exechub-db:/var/lib/postgresql/data"

volumes:
  exechub-db:
